ARG FRAPPE_BRANCH=version-15
ARG FRAPPE_IMAGE_PREFIX=frappe
ARG ERPNEXT_REPO=https://github.com/DriftingDesk/erpnextbuild1.git
ARG ERPNEXT_BRANCH=version-15

FROM ${FRAPPE_IMAGE_PREFIX}/build:${FRAPPE_BRANCH} AS builder

ARG FRAPPE_BRANCH=version-15
ARG FRAPPE_PATH=https://github.com/frappe/frappe
ARG ERPNEXT_REPO=https://github.com/DriftingDesk/erpnextbuild1.git
ARG ERPNEXT_BRANCH=version-15
ARG CACHE_BUST=""

USER root
COPY apps.json /opt/frappe/apps.json
RUN chown frappe:frappe /opt/frappe/apps.json

USER frappe

RUN : "${CACHE_BUST}" && \
  bench init \
    --apps_path=/opt/frappe/apps.json \
    --frappe-branch=${FRAPPE_BRANCH} \
    --frappe-path=${FRAPPE_PATH} \
    --no-procfile \
    --no-backups \
    --skip-redis-config-generation \
    --verbose \
    /home/frappe/frappe-bench && \
  cd /home/frappe/frappe-bench && \
  if [ ! -d apps/erpnext ]; then \
    bench get-app --branch=${ERPNEXT_BRANCH} ${ERPNEXT_REPO}; \
  fi && \
  if [ -d apps/erpnextbuild1 ] && [ ! -d apps/erpnext ]; then \
    mv apps/erpnextbuild1 apps/erpnext; \
  fi && \
  test -d apps/frappe && test -d apps/erpnext && \
  echo "{}" > sites/common_site_config.json && \
  find apps -mindepth 1 -path "*/.git" | xargs rm -fr

FROM ${FRAPPE_IMAGE_PREFIX}/base:${FRAPPE_BRANCH} AS backend

USER frappe

COPY --from=builder --chown=frappe:frappe /home/frappe/frappe-bench /home/frappe/frappe-bench

WORKDIR /home/frappe/frappe-bench

RUN cp -r /home/frappe/frappe-bench/sites/assets /home/frappe/frappe-bench/assets && \
  rm -rf /home/frappe/frappe-bench/sites/assets

VOLUME [ \
  "/home/frappe/frappe-bench/sites", \
  "/home/frappe/frappe-bench/logs" \
]

USER root
COPY resources/core/main-entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod 755 /usr/local/bin/entrypoint.sh

COPY resources/core/start.sh /usr/local/bin/start.sh
RUN chmod 755 /usr/local/bin/start.sh

USER frappe
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

CMD ["start.sh"]
