name: Build ERPNext Client Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - apps.json
      - images/erpnext-client/**
      - .github/workflows/build-erpnext-client.yml

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/driftingdesk/erpnext-client
  IMAGE_TAG: v15.114.0
  FRAPPE_BRANCH: version-15

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build test image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: images/erpnext-client/Containerfile
          build-args: |
            FRAPPE_BRANCH=${{ env.FRAPPE_BRANCH }}
            FRAPPE_PATH=https://github.com/frappe/frappe
            CACHE_BUST=${{ github.sha }}
          load: true
          tags: erpnext-client:test
          platforms: linux/amd64

      - name: Smoke test
        run: |
          docker run --rm --entrypoint bash erpnext-client:test -lc \
            'ls -la /home/frappe/frappe-bench/apps; test -d /home/frappe/frappe-bench/apps/frappe; test -d /home/frappe/frappe-bench/apps/erpnext'

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: images/erpnext-client/Containerfile
          build-args: |
            FRAPPE_BRANCH=${{ env.FRAPPE_BRANCH }}
            FRAPPE_PATH=https://github.com/frappe/frappe
            CACHE_BUST=${{ github.sha }}
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          platforms: linux/amd64
